services:
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: azurite
    ports:
      - "10000:10000" # Blob (nem kell most)
      - "10001:10001" # Queue (nem kell most)
      - "10002:10002" # Table — EZ kell!
    command: "azurite-table --location /data --debug /data/debug.log"
    volumes:
      - azurite_data:/data

volumes:
  azurite_data: